-- 코드를 입력하세요
SELECT 
    REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FOOD_TYPE, 
    REST_INFO.FAVORITES, REST_INFO.ADDRESS, ROUND(REST_REVIEW_AVG.AVG_SCORE, 2) AS SCORE
FROM REST_INFO
JOIN (
    SELECT REST_ID, AVG(REVIEW_SCORE) AS AVG_SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) AS REST_REVIEW_AVG ON REST_REVIEW_AVG.REST_ID = REST_INFO.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, REST_INFO.FAVORITES DESC;